export default [{
    id: 'krazydad-1-8-1',
    size: 8,
    ships:
        [{ size: 1, count: 3 },
            { size: 2, count: 3 },
            { size: 3, count: 2 },
            { size: 4, count: 1 }],
    shipsRows: [4, 1, 2, 2, 1, 4, 0, 5],
    shipsColumns: [1, 4, 2, 0, 4, 2, 5, 1],
    solution:
        [{ x: 0, y: 0, type: 'ship_single' },
            { x: 0, y: 2, type: 'ship_single' },
            { x: 0, y: 4, type: 'ship_top' },
            { x: 0, y: 6, type: 'ship_single' },
            { x: 1, y: 4, type: 'ship_bottom' },
            { x: 2, y: 1, type: 'ship_top' },
            { x: 2, y: 6, type: 'ship_top' },
            { x: 3, y: 1, type: 'ship' },
            { x: 3, y: 6, type: 'ship_bottom' },
            { x: 4, y: 1, type: 'ship_bottom' },
            { x: 5, y: 4, type: 'ship_left' },
            { x: 5, y: 5, type: 'ship' },
            { x: 5, y: 6, type: 'ship' },
            { x: 5, y: 7, type: 'ship_right' },
            { x: 7, y: 1, type: 'ship_left' },
            { x: 7, y: 2, type: 'ship_right' },
            { x: 7, y: 4, type: 'ship_left' },
            { x: 7, y: 5, type: 'ship' },
            { x: 7, y: 6, type: 'ship_right' }],
    puzzle:
        [{ x: 1, y: 4, type: 'ship_bottom' },
            { x: 7, y: 1, type: 'ship_left' }],
},
    {
        id: 'krazydad-1-8-2',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 1, 3, 2, 2, 4, 0, 4],
        shipsColumns: [2, 1, 4, 3, 0, 4, 1, 4],
        solution:
            [{ x: 0, y: 2, type: 'ship_left' },
                { x: 0, y: 3, type: 'ship_right' },
                { x: 0, y: 5, type: 'ship_single' },
                { x: 1, y: 7, type: 'ship_top' },
                { x: 2, y: 2, type: 'ship_single' },
                { x: 2, y: 5, type: 'ship_top' },
                { x: 2, y: 7, type: 'ship' },
                { x: 3, y: 5, type: 'ship_bottom' },
                { x: 3, y: 7, type: 'ship_bottom' },
                { x: 4, y: 2, type: 'ship_left' },
                { x: 4, y: 3, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 6, type: 'ship' },
                { x: 5, y: 7, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 1, type: 'ship' },
                { x: 7, y: 2, type: 'ship' },
                { x: 7, y: 3, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 5, type: 'water' },
                { x: 4, y: 3, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-8-3',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [5, 2, 1, 3, 1, 1, 4, 2],
        shipsColumns: [2, 1, 4, 2, 2, 1, 4, 3],
        solution:
            [{ x: 0, y: 2, type: 'ship_top' },
                { x: 0, y: 4, type: 'ship_left' },
                { x: 0, y: 5, type: 'ship' },
                { x: 0, y: 6, type: 'ship' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship_bottom' },
                { x: 2, y: 7, type: 'ship_single' },
                { x: 3, y: 1, type: 'ship_left' },
                { x: 3, y: 2, type: 'ship' },
                { x: 3, y: 3, type: 'ship_right' },
                { x: 4, y: 6, type: 'ship_top' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 6, y: 0, type: 'ship_single' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 4, type: 'ship_right' },
                { x: 7, y: 6, type: 'ship_left' },
                { x: 7, y: 7, type: 'ship_right' }],
        puzzle:
            [{ x: 3, y: 3, type: 'ship_right' },
                { x: 6, y: 0, type: 'ship_single' },
                { x: 6, y: 3, type: 'ship' }],
    },
    {
        id: 'krazydad-1-8-4',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 3, 2, 2, 3, 3, 2, 3],
        shipsColumns: [1, 4, 0, 4, 0, 3, 0, 7],
        solution:
            [{ x: 0, y: 7, type: 'ship_top' },
                { x: 1, y: 3, type: 'ship_single' },
                { x: 1, y: 5, type: 'ship_top' },
                { x: 1, y: 7, type: 'ship' },
                { x: 2, y: 5, type: 'ship_bottom' },
                { x: 2, y: 7, type: 'ship_bottom' },
                { x: 3, y: 1, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_single' },
                { x: 4, y: 1, type: 'ship' },
                { x: 4, y: 5, type: 'ship_single' },
                { x: 4, y: 7, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 3, type: 'ship_top' },
                { x: 5, y: 7, type: 'ship' },
                { x: 6, y: 3, type: 'ship_bottom' },
                { x: 6, y: 7, type: 'ship' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 1, type: 'ship_right' },
                { x: 7, y: 7, type: 'ship_bottom' }],
        puzzle:
            [{ x: 1, y: 5, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_single' },
                { x: 7, y: 1, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-8-5',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 3, 1, 5, 1, 2, 4, 2],
        shipsColumns: [4, 1, 2, 4, 1, 1, 4, 2],
        solution:
            [{ x: 0, y: 3, type: 'ship_top' },
                { x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 3, type: 'ship_bottom' },
                { x: 1, y: 6, type: 'ship_top' },
                { x: 2, y: 6, type: 'ship' },
                { x: 3, y: 0, type: 'ship_top' },
                { x: 3, y: 2, type: 'ship_left' },
                { x: 3, y: 3, type: 'ship' },
                { x: 3, y: 4, type: 'ship_right' },
                { x: 3, y: 6, type: 'ship_bottom' },
                { x: 4, y: 0, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_single' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 6, y: 0, type: 'ship_left' },
                { x: 6, y: 1, type: 'ship' },
                { x: 6, y: 2, type: 'ship' },
                { x: 6, y: 3, type: 'ship_right' },
                { x: 7, y: 6, type: 'ship_left' },
                { x: 7, y: 7, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 3, type: 'ship_bottom' },
                { x: 2, y: 0, type: 'water' },
                { x: 6, y: 0, type: 'ship_left' },
                { x: 7, y: 6, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-8-6',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 2, 2, 3, 2, 2, 3, 3],
        shipsColumns: [2, 0, 6, 0, 4, 1, 4, 2],
        solution:
            [{ x: 0, y: 5, type: 'ship_left' },
                { x: 0, y: 6, type: 'ship_right' },
                { x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship_top' },
                { x: 2, y: 2, type: 'ship' },
                { x: 2, y: 7, type: 'ship_top' },
                { x: 3, y: 2, type: 'ship' },
                { x: 3, y: 4, type: 'ship_top' },
                { x: 3, y: 7, type: 'ship_bottom' },
                { x: 4, y: 2, type: 'ship_bottom' },
                { x: 4, y: 4, type: 'ship' },
                { x: 5, y: 4, type: 'ship_bottom' },
                { x: 5, y: 6, type: 'ship_top' },
                { x: 6, y: 0, type: 'ship_single' },
                { x: 6, y: 2, type: 'ship_top' },
                { x: 6, y: 6, type: 'ship' },
                { x: 7, y: 2, type: 'ship_bottom' },
                { x: 7, y: 4, type: 'ship_single' },
                { x: 7, y: 6, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_right' },
                { x: 6, y: 4, type: 'water' },
                { x: 7, y: 6, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-8-7',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 1, 4, 0, 3, 1, 4, 2],
        shipsColumns: [0, 4, 1, 4, 4, 2, 2, 2],
        solution:
            [{ x: 0, y: 1, type: 'ship_single' },
                { x: 0, y: 3, type: 'ship_left' },
                { x: 0, y: 4, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_top' },
                { x: 1, y: 6, type: 'ship_bottom' },
                { x: 2, y: 1, type: 'ship_left' },
                { x: 2, y: 2, type: 'ship' },
                { x: 2, y: 3, type: 'ship' },
                { x: 2, y: 4, type: 'ship_right' },
                { x: 4, y: 3, type: 'ship_left' },
                { x: 4, y: 4, type: 'ship' },
                { x: 4, y: 5, type: 'ship_right' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 6, y: 1, type: 'ship_top' },
                { x: 6, y: 3, type: 'ship_left' },
                { x: 6, y: 4, type: 'ship' },
                { x: 6, y: 5, type: 'ship_right' },
                { x: 7, y: 1, type: 'ship_bottom' },
                { x: 7, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_top' },
                { x: 7, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-8-8',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 3, 2, 4, 1, 2, 0, 5],
        shipsColumns: [1, 3, 3, 3, 1, 1, 2, 5],
        solution:
            [{ x: 0, y: 6, type: 'ship_left' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 1, y: 1, type: 'ship_left' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 3, type: 'ship_right' },
                { x: 2, y: 6, type: 'ship_left' },
                { x: 2, y: 7, type: 'ship_right' },
                { x: 3, y: 0, type: 'ship_left' },
                { x: 3, y: 1, type: 'ship' },
                { x: 3, y: 2, type: 'ship' },
                { x: 3, y: 3, type: 'ship_right' },
                { x: 4, y: 7, type: 'ship_top' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 5, y: 7, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'ship_single' },
                { x: 7, y: 3, type: 'ship_left' },
                { x: 7, y: 4, type: 'ship' },
                { x: 7, y: 5, type: 'ship_right' },
                { x: 7, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 7, y: 3, type: 'ship_left' },
                { x: 7, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-8-9',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 0, 4, 0, 3, 3, 3, 3],
        shipsColumns: [3, 1, 3, 0, 4, 1, 6, 1],
        solution:
            [{ x: 0, y: 2, type: 'ship_single' },
                { x: 0, y: 6, type: 'ship_left' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 2, y: 5, type: 'ship' },
                { x: 2, y: 6, type: 'ship_right' },
                { x: 4, y: 0, type: 'ship_top' },
                { x: 4, y: 4, type: 'ship_top' },
                { x: 4, y: 6, type: 'ship_top' },
                { x: 5, y: 0, type: 'ship_bottom' },
                { x: 5, y: 4, type: 'ship' },
                { x: 5, y: 6, type: 'ship' },
                { x: 6, y: 2, type: 'ship_top' },
                { x: 6, y: 4, type: 'ship_bottom' },
                { x: 6, y: 6, type: 'ship' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 2, type: 'ship_bottom' },
                { x: 7, y: 6, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 1, type: 'water' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 4, y: 2, type: 'water' },
                { x: 5, y: 0, type: 'ship_bottom' },
                { x: 7, y: 0, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-8-10',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 1, 5, 0, 3, 3, 0, 4],
        shipsColumns: [2, 2, 3, 2, 1, 3, 2, 4],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship_right' },
                { x: 0, y: 5, type: 'ship_single' },
                { x: 1, y: 7, type: 'ship_top' },
                { x: 2, y: 1, type: 'ship_left' },
                { x: 2, y: 2, type: 'ship' },
                { x: 2, y: 3, type: 'ship' },
                { x: 2, y: 4, type: 'ship_right' },
                { x: 2, y: 7, type: 'ship_bottom' },
                { x: 4, y: 5, type: 'ship_left' },
                { x: 4, y: 6, type: 'ship' },
                { x: 4, y: 7, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 2, type: 'ship_left' },
                { x: 5, y: 3, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 5, type: 'ship_left' },
                { x: 7, y: 6, type: 'ship' },
                { x: 7, y: 7, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 3, type: 'water' },
                { x: 2, y: 4, type: 'ship_right' },
                { x: 4, y: 2, type: 'water' }],
    },
    {
        id: 'krazydad-1-8-11',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 2, 4, 2, 0, 6, 0, 3],
        shipsColumns: [2, 2, 4, 1, 0, 5, 2, 3],
        solution:
            [{ x: 0, y: 2, type: 'ship_single' },
                { x: 0, y: 7, type: 'ship_top' },
                { x: 1, y: 5, type: 'ship_top' },
                { x: 1, y: 7, type: 'ship_bottom' },
                { x: 2, y: 0, type: 'ship_left' },
                { x: 2, y: 1, type: 'ship' },
                { x: 2, y: 2, type: 'ship_right' },
                { x: 2, y: 5, type: 'ship' },
                { x: 3, y: 5, type: 'ship_bottom' },
                { x: 3, y: 7, type: 'ship_single' },
                { x: 5, y: 0, type: 'ship_left' },
                { x: 5, y: 1, type: 'ship' },
                { x: 5, y: 2, type: 'ship' },
                { x: 5, y: 3, type: 'ship_right' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 6, type: 'ship_right' },
                { x: 7, y: 2, type: 'ship_single' },
                { x: 7, y: 5, type: 'ship_left' },
                { x: 7, y: 6, type: 'ship_right' }],
        puzzle: [{ x: 1, y: 7, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-8-12',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 2, 2, 1, 3, 2, 5, 0],
        shipsColumns: [2, 3, 3, 0, 4, 2, 0, 5],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship_right' },
                { x: 0, y: 5, type: 'ship_top' },
                { x: 0, y: 7, type: 'ship_top' },
                { x: 1, y: 5, type: 'ship_bottom' },
                { x: 1, y: 7, type: 'ship' },
                { x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 7, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_top' },
                { x: 4, y: 0, type: 'ship_single' },
                { x: 4, y: 2, type: 'ship_single' },
                { x: 4, y: 4, type: 'ship' },
                { x: 5, y: 4, type: 'ship' },
                { x: 5, y: 7, type: 'ship_top' },
                { x: 6, y: 0, type: 'ship_left' },
                { x: 6, y: 1, type: 'ship' },
                { x: 6, y: 2, type: 'ship_right' },
                { x: 6, y: 4, type: 'ship_bottom' },
                { x: 6, y: 7, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 0, type: 'water' },
                { x: 0, y: 5, type: 'ship_top' },
                { x: 4, y: 1, type: 'water' }],
    },
    {
        id: 'krazydad-1-8-13',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 1, 4, 0, 5, 2, 3, 2],
        shipsColumns: [4, 1, 5, 0, 3, 1, 4, 1],
        solution:
            [{ x: 0, y: 2, type: 'ship_single' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 4, type: 'ship_top' },
                { x: 2, y: 1, type: 'ship_left' },
                { x: 2, y: 2, type: 'ship_right' },
                { x: 2, y: 4, type: 'ship_bottom' },
                { x: 2, y: 7, type: 'ship_single' },
                { x: 4, y: 0, type: 'ship_top' },
                { x: 4, y: 2, type: 'ship_top' },
                { x: 4, y: 4, type: 'ship_left' },
                { x: 4, y: 5, type: 'ship' },
                { x: 4, y: 6, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship' },
                { x: 5, y: 2, type: 'ship' },
                { x: 6, y: 0, type: 'ship' },
                { x: 6, y: 2, type: 'ship_bottom' },
                { x: 6, y: 6, type: 'ship_top' },
                { x: 7, y: 0, type: 'ship_bottom' },
                { x: 7, y: 6, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 4, type: 'ship_top' },
                { x: 6, y: 2, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-8-14',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 0, 4, 1, 1, 4, 4, 1],
        shipsColumns: [5, 0, 4, 1, 2, 3, 0, 4],
        solution:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 0, y: 2, type: 'ship_single' },
                { x: 0, y: 4, type: 'ship_left' },
                { x: 0, y: 5, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship_left' },
                { x: 2, y: 3, type: 'ship' },
                { x: 2, y: 4, type: 'ship_right' },
                { x: 3, y: 7, type: 'ship_top' },
                { x: 4, y: 7, type: 'ship' },
                { x: 5, y: 0, type: 'ship_top' },
                { x: 5, y: 2, type: 'ship_top' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 5, y: 7, type: 'ship' },
                { x: 6, y: 0, type: 'ship' },
                { x: 6, y: 2, type: 'ship_bottom' },
                { x: 6, y: 5, type: 'ship_bottom' },
                { x: 6, y: 7, type: 'ship_bottom' },
                { x: 7, y: 0, type: 'ship_bottom' }],
        puzzle:
            [{ x: 2, y: 2, type: 'ship_left' },
                { x: 3, y: 0, type: 'water' },
                { x: 6, y: 5, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-8-15',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 1, 0, 5, 0, 6, 1, 2],
        shipsColumns: [3, 1, 3, 2, 3, 2, 2, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 0, y: 2, type: 'ship_left' },
                { x: 0, y: 3, type: 'ship' },
                { x: 0, y: 4, type: 'ship_right' },
                { x: 1, y: 6, type: 'ship_single' },
                { x: 3, y: 0, type: 'ship_left' },
                { x: 3, y: 1, type: 'ship' },
                { x: 3, y: 2, type: 'ship_right' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 7, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 2, type: 'ship_left' },
                { x: 5, y: 3, type: 'ship' },
                { x: 5, y: 4, type: 'ship' },
                { x: 5, y: 5, type: 'ship_right' },
                { x: 5, y: 7, type: 'ship_top' },
                { x: 6, y: 7, type: 'ship_bottom' },
                { x: 7, y: 4, type: 'ship_left' },
                { x: 7, y: 5, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 1, y: 6, type: 'ship_single' },
                { x: 7, y: 4, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-8-16',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [5, 1, 0, 3, 0, 4, 0, 6],
        shipsColumns: [4, 2, 2, 2, 3, 1, 3, 2],
        solution:
            [{ x: 0, y: 0, type: 'ship_top' },
                { x: 0, y: 2, type: 'ship_left' },
                { x: 0, y: 3, type: 'ship' },
                { x: 0, y: 4, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_single' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 7, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship_left' },
                { x: 5, y: 1, type: 'ship' },
                { x: 5, y: 2, type: 'ship_right' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 1, type: 'ship_right' },
                { x: 7, y: 3, type: 'ship_left' },
                { x: 7, y: 4, type: 'ship' },
                { x: 7, y: 5, type: 'ship' },
                { x: 7, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 2, type: 'ship_left' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 7, y: 6, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-8-17',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 2, 5, 1, 3, 2, 2, 1],
        shipsColumns: [5, 0, 5, 0, 2, 2, 2, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_top' },
                { x: 0, y: 2, type: 'ship_top' },
                { x: 0, y: 7, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship' },
                { x: 1, y: 2, type: 'ship_bottom' },
                { x: 2, y: 0, type: 'ship_bottom' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 2, y: 5, type: 'ship' },
                { x: 2, y: 6, type: 'ship' },
                { x: 2, y: 7, type: 'ship_right' },
                { x: 3, y: 2, type: 'ship_single' },
                { x: 4, y: 4, type: 'ship_left' },
                { x: 4, y: 5, type: 'ship' },
                { x: 4, y: 6, type: 'ship_right' },
                { x: 5, y: 0, type: 'ship_top' },
                { x: 5, y: 2, type: 'ship_top' },
                { x: 6, y: 0, type: 'ship_bottom' },
                { x: 6, y: 2, type: 'ship_bottom' },
                { x: 7, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 5, type: 'water' },
                { x: 0, y: 6, type: 'water' },
                { x: 2, y: 0, type: 'ship_bottom' },
                { x: 2, y: 7, type: 'ship_right' },
                { x: 4, y: 4, type: 'ship_left' },
                { x: 6, y: 6, type: 'water' },
                { x: 7, y: 6, type: 'water' }],
    },
    {
        id: 'krazydad-1-8-18',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 1, 4, 3, 1, 5, 1, 2],
        shipsColumns: [0, 5, 1, 3, 1, 5, 1, 3],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship_right' },
                { x: 1, y: 5, type: 'ship_top' },
                { x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 3, type: 'ship_top' },
                { x: 2, y: 5, type: 'ship' },
                { x: 2, y: 7, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_bottom' },
                { x: 3, y: 5, type: 'ship_bottom' },
                { x: 3, y: 7, type: 'ship_bottom' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship' },
                { x: 5, y: 4, type: 'ship_left' },
                { x: 5, y: 5, type: 'ship' },
                { x: 5, y: 6, type: 'ship' },
                { x: 5, y: 7, type: 'ship_right' },
                { x: 6, y: 1, type: 'ship_bottom' },
                { x: 7, y: 3, type: 'ship_single' },
                { x: 7, y: 5, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 2, type: 'ship_right' },
                { x: 5, y: 3, type: 'water' }],
    },
    {
        id: 'krazydad-1-8-19',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 5, 1, 3, 1, 4, 0, 4],
        shipsColumns: [1, 5, 0, 2, 3, 2, 3, 3],
        solution:
            [{ x: 0, y: 1, type: 'ship_top' },
                { x: 1, y: 1, type: 'ship' },
                { x: 1, y: 3, type: 'ship_left' },
                { x: 1, y: 4, type: 'ship' },
                { x: 1, y: 5, type: 'ship' },
                { x: 1, y: 6, type: 'ship_right' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_single' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 7, type: 'ship_right' },
                { x: 4, y: 1, type: 'ship_single' },
                { x: 5, y: 3, type: 'ship_left' },
                { x: 5, y: 4, type: 'ship' },
                { x: 5, y: 5, type: 'ship_right' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 1, type: 'ship_right' },
                { x: 7, y: 6, type: 'ship_left' },
                { x: 7, y: 7, type: 'ship_right' }],
        puzzle:
            [{ x: 3, y: 7, type: 'ship_right' },
                { x: 5, y: 5, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 6, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-8-20',
        size: 8,
        ships:
            [{ size: 1, count: 3 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [0, 3, 2, 3, 3, 3, 0, 5],
        shipsColumns: [1, 3, 2, 3, 1, 5, 1, 3],
        solution:
            [{ x: 1, y: 1, type: 'ship_left' },
                { x: 1, y: 2, type: 'ship_right' },
                { x: 1, y: 5, type: 'ship_top' },
                { x: 2, y: 5, type: 'ship' },
                { x: 2, y: 7, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_top' },
                { x: 3, y: 5, type: 'ship' },
                { x: 3, y: 7, type: 'ship_bottom' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 4, y: 3, type: 'ship' },
                { x: 4, y: 5, type: 'ship_bottom' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 2, type: 'ship_single' },
                { x: 7, y: 4, type: 'ship_left' },
                { x: 7, y: 5, type: 'ship' },
                { x: 7, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 7, type: 'water' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-1',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 1, 5, 0, 2, 3, 2, 1, 3],
        shipsColumns: [0, 7, 0, 1, 1, 2, 4, 2, 3],
        solution:
            [{ x: 0, y: 1, type: 'ship_top' },
                { x: 0, y: 6, type: 'ship_left' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 1, y: 1, type: 'ship' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 2, y: 5, type: 'ship' },
                { x: 2, y: 6, type: 'ship_right' },
                { x: 2, y: 8, type: 'ship_single' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship' },
                { x: 5, y: 6, type: 'ship_top' },
                { x: 5, y: 8, type: 'ship_bottom' },
                { x: 6, y: 1, type: 'ship' },
                { x: 6, y: 6, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'ship_bottom' },
                { x: 8, y: 3, type: 'ship_single' },
                { x: 8, y: 5, type: 'ship_single' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 2, y: 4, type: 'ship_left' },
                { x: 5, y: 8, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'ship_bottom' },
                { x: 8, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-2',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 2, 1, 0, 3, 3, 4, 1, 4],
        shipsColumns: [5, 0, 4, 2, 0, 3, 2, 1, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 0, y: 2, type: 'ship_top' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 7, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship_bottom' },
                { x: 4, y: 0, type: 'ship_top' },
                { x: 4, y: 5, type: 'ship_single' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 0, type: 'ship' },
                { x: 5, y: 3, type: 'ship_single' },
                { x: 5, y: 8, type: 'ship' },
                { x: 6, y: 0, type: 'ship' },
                { x: 6, y: 5, type: 'ship_left' },
                { x: 6, y: 6, type: 'ship_right' },
                { x: 6, y: 8, type: 'ship_bottom' },
                { x: 7, y: 0, type: 'ship_bottom' },
                { x: 8, y: 2, type: 'ship_left' },
                { x: 8, y: 3, type: 'ship_right' },
                { x: 8, y: 5, type: 'ship_left' },
                { x: 8, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 7, type: 'ship_single' },
                { x: 6, y: 2, type: 'water' },
                { x: 7, y: 0, type: 'ship_bottom' },
                { x: 8, y: 8, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-3',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 1, 4, 0, 4, 1, 2, 2, 3],
        shipsColumns: [1, 4, 1, 0, 2, 2, 3, 2, 5],
        solution:
            [{ x: 0, y: 1, type: 'ship_top' },
                { x: 0, y: 6, type: 'ship_left' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 1, y: 1, type: 'ship' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 2, y: 4, type: 'ship_single' },
                { x: 2, y: 7, type: 'ship_left' },
                { x: 2, y: 8, type: 'ship_right' },
                { x: 4, y: 0, type: 'ship_left' },
                { x: 4, y: 1, type: 'ship_right' },
                { x: 4, y: 6, type: 'ship_single' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 8, type: 'ship' },
                { x: 6, y: 5, type: 'ship_single' },
                { x: 6, y: 8, type: 'ship' },
                { x: 7, y: 2, type: 'ship_single' },
                { x: 7, y: 8, type: 'ship_bottom' },
                { x: 8, y: 4, type: 'ship_left' },
                { x: 8, y: 5, type: 'ship' },
                { x: 8, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 2, y: 8, type: 'ship_right' },
                { x: 4, y: 0, type: 'ship_left' },
                { x: 6, y: 5, type: 'ship_single' },
                { x: 7, y: 1, type: 'water' },
                { x: 7, y: 8, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-9-4',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 0, 2, 3, 1, 1, 4, 0, 5],
        shipsColumns: [1, 2, 3, 3, 2, 1, 2, 1, 5],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship' },
                { x: 0, y: 3, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 2, y: 4, type: 'ship_single' },
                { x: 2, y: 6, type: 'ship_single' },
                { x: 3, y: 0, type: 'ship_left' },
                { x: 3, y: 1, type: 'ship_right' },
                { x: 3, y: 8, type: 'ship_top' },
                { x: 4, y: 8, type: 'ship' },
                { x: 5, y: 8, type: 'ship' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 4, type: 'ship_right' },
                { x: 6, y: 8, type: 'ship_bottom' },
                { x: 8, y: 2, type: 'ship_left' },
                { x: 8, y: 3, type: 'ship_right' },
                { x: 8, y: 5, type: 'ship_single' },
                { x: 8, y: 7, type: 'ship_left' },
                { x: 8, y: 8, type: 'ship_right' }],
        puzzle:
            [{ x: 2, y: 4, type: 'ship_single' },
                { x: 3, y: 1, type: 'ship_right' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 6, type: 'water' },
                { x: 8, y: 1, type: 'water' },
                { x: 8, y: 3, type: 'ship_right' },
                { x: 8, y: 6, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-5',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 3, 3, 2, 1, 4, 0, 4, 1],
        shipsColumns: [5, 1, 5, 1, 1, 1, 2, 1, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_top' },
                { x: 0, y: 4, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_bottom' },
                { x: 1, y: 2, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship_top' },
                { x: 2, y: 2, type: 'ship' },
                { x: 2, y: 6, type: 'ship_single' },
                { x: 2, y: 8, type: 'ship' },
                { x: 3, y: 2, type: 'ship_bottom' },
                { x: 3, y: 8, type: 'ship_bottom' },
                { x: 4, y: 0, type: 'ship_top' },
                { x: 5, y: 0, type: 'ship_bottom' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 6, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_left' },
                { x: 7, y: 1, type: 'ship' },
                { x: 7, y: 2, type: 'ship' },
                { x: 7, y: 3, type: 'ship_right' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 4, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_bottom' },
                { x: 3, y: 0, type: 'water' },
                { x: 8, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-6',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 3, 2, 1, 4, 3, 0, 5, 1],
        shipsColumns: [2, 2, 3, 2, 3, 2, 1, 2, 3],
        solution:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 1, type: 'ship_left' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 3, type: 'ship_right' },
                { x: 2, y: 5, type: 'ship_single' },
                { x: 2, y: 8, type: 'ship_top' },
                { x: 3, y: 8, type: 'ship_bottom' },
                { x: 4, y: 0, type: 'ship_left' },
                { x: 4, y: 1, type: 'ship' },
                { x: 4, y: 2, type: 'ship_right' },
                { x: 4, y: 4, type: 'ship_top' },
                { x: 5, y: 4, type: 'ship_bottom' },
                { x: 5, y: 7, type: 'ship_left' },
                { x: 5, y: 8, type: 'ship_right' },
                { x: 7, y: 2, type: 'ship_left' },
                { x: 7, y: 3, type: 'ship' },
                { x: 7, y: 4, type: 'ship' },
                { x: 7, y: 5, type: 'ship_right' },
                { x: 7, y: 7, type: 'ship_single' },
                { x: 8, y: 0, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 3, type: 'ship_right' },
                { x: 5, y: 5, type: 'water' },
                { x: 7, y: 1, type: 'water' },
                { x: 7, y: 3, type: 'ship' },
                { x: 7, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-7',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 5, 2, 2, 2, 3, 1, 2, 2],
        shipsColumns: [2, 2, 3, 3, 0, 4, 2, 3, 1],
        solution:
            [{ x: 0, y: 2, type: 'ship_top' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 5, type: 'ship_left' },
                { x: 1, y: 6, type: 'ship' },
                { x: 1, y: 7, type: 'ship' },
                { x: 1, y: 8, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship_bottom' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 7, type: 'ship_right' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 4, y: 3, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 6, y: 5, type: 'ship' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 5, type: 'ship_bottom' },
                { x: 8, y: 3, type: 'ship_single' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 3, y: 7, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 8, y: 5, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-8',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 1, 3, 1, 1, 5, 2, 2, 3],
        shipsColumns: [0, 3, 3, 2, 0, 4, 2, 0, 6],
        solution:
            [{ x: 0, y: 1, type: 'ship_single' },
                { x: 0, y: 8, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship_bottom' },
                { x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 3, type: 'ship_single' },
                { x: 2, y: 6, type: 'ship_top' },
                { x: 3, y: 6, type: 'ship_bottom' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship_left' },
                { x: 5, y: 2, type: 'ship' },
                { x: 5, y: 3, type: 'ship_right' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 5, y: 8, type: 'ship' },
                { x: 6, y: 5, type: 'ship' },
                { x: 6, y: 8, type: 'ship_bottom' },
                { x: 7, y: 2, type: 'ship_top' },
                { x: 7, y: 5, type: 'ship' },
                { x: 8, y: 2, type: 'ship_bottom' },
                { x: 8, y: 5, type: 'ship_bottom' },
                { x: 8, y: 8, type: 'ship_single' }],
        puzzle:
            [{ x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 3, type: 'ship_single' },
                { x: 2, y: 6, type: 'ship_top' }],
    },
    {
        id: 'krazydad-1-9-9',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [0, 5, 2, 3, 3, 2, 1, 2, 2],
        shipsColumns: [3, 3, 1, 5, 1, 0, 5, 0, 2],
        solution:
            [{ x: 1, y: 0, type: 'ship_left' },
                { x: 1, y: 1, type: 'ship' },
                { x: 1, y: 2, type: 'ship_right' },
                { x: 1, y: 4, type: 'ship_single' },
                { x: 1, y: 6, type: 'ship_top' },
                { x: 2, y: 6, type: 'ship' },
                { x: 2, y: 8, type: 'ship_single' },
                { x: 3, y: 1, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_top' },
                { x: 3, y: 6, type: 'ship' },
                { x: 4, y: 1, type: 'ship_bottom' },
                { x: 4, y: 3, type: 'ship' },
                { x: 4, y: 6, type: 'ship_bottom' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 5, y: 8, type: 'ship_single' },
                { x: 6, y: 0, type: 'ship_top' },
                { x: 7, y: 0, type: 'ship_bottom' },
                { x: 7, y: 3, type: 'ship_top' },
                { x: 8, y: 3, type: 'ship_bottom' },
                { x: 8, y: 6, type: 'ship_single' }],
        puzzle:
            [{ x: 3, y: 1, type: 'ship_top' },
                { x: 7, y: 3, type: 'ship_top' },
                { x: 8, y: 6, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-10',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 4, 1, 0, 6, 1, 2, 3, 1],
        shipsColumns: [3, 2, 3, 3, 1, 1, 1, 3, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_top' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_bottom' },
                { x: 1, y: 2, type: 'ship_left' },
                { x: 1, y: 3, type: 'ship' },
                { x: 1, y: 4, type: 'ship_right' },
                { x: 2, y: 8, type: 'ship_single' },
                { x: 4, y: 0, type: 'ship_left' },
                { x: 4, y: 1, type: 'ship' },
                { x: 4, y: 2, type: 'ship' },
                { x: 4, y: 3, type: 'ship_right' },
                { x: 4, y: 7, type: 'ship_left' },
                { x: 4, y: 8, type: 'ship_right' },
                { x: 5, y: 5, type: 'ship_single' },
                { x: 6, y: 7, type: 'ship_left' },
                { x: 6, y: 8, type: 'ship_right' },
                { x: 7, y: 1, type: 'ship_left' },
                { x: 7, y: 2, type: 'ship' },
                { x: 7, y: 3, type: 'ship_right' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 8, type: 'water' },
                { x: 1, y: 4, type: 'ship_right' },
                { x: 6, y: 8, type: 'ship_right' },
                { x: 8, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-11',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 3, 2, 2, 2, 4, 1, 0, 4],
        shipsColumns: [0, 4, 0, 2, 2, 3, 2, 3, 4],
        solution:
            [{ x: 0, y: 1, type: 'ship_single' },
                { x: 0, y: 7, type: 'ship_single' },
                { x: 1, y: 3, type: 'ship_left' },
                { x: 1, y: 4, type: 'ship' },
                { x: 1, y: 5, type: 'ship_right' },
                { x: 2, y: 7, type: 'ship_left' },
                { x: 2, y: 8, type: 'ship_right' },
                { x: 3, y: 1, type: 'ship_top' },
                { x: 3, y: 4, type: 'ship_single' },
                { x: 4, y: 1, type: 'ship' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 6, type: 'ship_right' },
                { x: 5, y: 8, type: 'ship_bottom' },
                { x: 6, y: 3, type: 'ship_single' },
                { x: 8, y: 5, type: 'ship_left' },
                { x: 8, y: 6, type: 'ship' },
                { x: 8, y: 7, type: 'ship' },
                { x: 8, y: 8, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 7, type: 'ship_single' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 8, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-9-12',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 0, 2, 1, 4, 1, 3, 4, 1],
        shipsColumns: [3, 2, 1, 5, 0, 3, 1, 3, 2],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship' },
                { x: 0, y: 3, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 2, y: 5, type: 'ship_top' },
                { x: 2, y: 8, type: 'ship_single' },
                { x: 3, y: 5, type: 'ship_bottom' },
                { x: 4, y: 1, type: 'ship_single' },
                { x: 4, y: 3, type: 'ship_top' },
                { x: 4, y: 7, type: 'ship_left' },
                { x: 4, y: 8, type: 'ship_right' },
                { x: 5, y: 3, type: 'ship' },
                { x: 6, y: 0, type: 'ship_top' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 7, type: 'ship_top' },
                { x: 7, y: 0, type: 'ship' },
                { x: 7, y: 3, type: 'ship_bottom' },
                { x: 7, y: 5, type: 'ship_single' },
                { x: 7, y: 7, type: 'ship_bottom' },
                { x: 8, y: 0, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 2, y: 7, type: 'water' },
                { x: 3, y: 5, type: 'ship_bottom' },
                { x: 4, y: 1, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-13',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [5, 2, 1, 2, 2, 3, 1, 0, 4],
        shipsColumns: [1, 3, 1, 5, 1, 2, 2, 3, 2],
        solution:
            [{ x: 0, y: 3, type: 'ship_left' },
                { x: 0, y: 4, type: 'ship' },
                { x: 0, y: 5, type: 'ship' },
                { x: 0, y: 6, type: 'ship_right' },
                { x: 0, y: 8, type: 'ship_top' },
                { x: 1, y: 1, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship_bottom' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 3, y: 3, type: 'ship_single' },
                { x: 3, y: 7, type: 'ship_top' },
                { x: 4, y: 5, type: 'ship_single' },
                { x: 4, y: 7, type: 'ship' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 3, type: 'ship_top' },
                { x: 5, y: 7, type: 'ship_bottom' },
                { x: 6, y: 3, type: 'ship_bottom' },
                { x: 8, y: 1, type: 'ship_left' },
                { x: 8, y: 2, type: 'ship' },
                { x: 8, y: 3, type: 'ship_right' },
                { x: 8, y: 6, type: 'ship_single' }],
        puzzle:
            [{ x: 1, y: 8, type: 'ship_bottom' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 3, y: 3, type: 'ship_single' },
                { x: 4, y: 0, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-14',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 2, 1, 4, 2, 2, 0, 6, 0],
        shipsColumns: [2, 2, 3, 1, 2, 3, 2, 1, 4],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship_right' },
                { x: 0, y: 5, type: 'ship_top' },
                { x: 1, y: 5, type: 'ship_bottom' },
                { x: 1, y: 8, type: 'ship_single' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 3, y: 2, type: 'ship_left' },
                { x: 3, y: 3, type: 'ship' },
                { x: 3, y: 4, type: 'ship_right' },
                { x: 3, y: 8, type: 'ship_top' },
                { x: 4, y: 6, type: 'ship_single' },
                { x: 4, y: 8, type: 'ship' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 8, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'ship_left' },
                { x: 7, y: 2, type: 'ship_right' },
                { x: 7, y: 4, type: 'ship_left' },
                { x: 7, y: 5, type: 'ship' },
                { x: 7, y: 6, type: 'ship' },
                { x: 7, y: 7, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 5, type: 'ship_bottom' },
                { x: 1, y: 8, type: 'ship_single' },
                { x: 3, y: 1, type: 'water' },
                { x: 4, y: 0, type: 'water' },
                { x: 5, y: 2, type: 'water' },
                { x: 7, y: 4, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-9-15',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 3, 2, 4, 2, 4, 1, 3, 0],
        shipsColumns: [3, 1, 4, 1, 5, 0, 0, 5, 1],
        solution:
            [{ x: 0, y: 1, type: 'ship_single' },
                { x: 1, y: 4, type: 'ship_single' },
                { x: 1, y: 7, type: 'ship_left' },
                { x: 1, y: 8, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_top' },
                { x: 2, y: 2, type: 'ship_top' },
                { x: 3, y: 0, type: 'ship_bottom' },
                { x: 3, y: 2, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_top' },
                { x: 3, y: 7, type: 'ship_top' },
                { x: 4, y: 4, type: 'ship' },
                { x: 4, y: 7, type: 'ship' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 5, y: 4, type: 'ship_bottom' },
                { x: 5, y: 7, type: 'ship' },
                { x: 6, y: 7, type: 'ship_bottom' },
                { x: 7, y: 2, type: 'ship_left' },
                { x: 7, y: 3, type: 'ship' },
                { x: 7, y: 4, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 4, type: 'ship_single' },
                { x: 2, y: 0, type: 'ship_top' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 7, y: 7, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-16',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 4, 2, 2, 3, 1, 5, 0, 1],
        shipsColumns: [2, 4, 0, 3, 1, 3, 1, 6, 0],
        solution:
            [{ x: 0, y: 0, type: 'ship_left' },
                { x: 0, y: 1, type: 'ship_right' },
                { x: 1, y: 3, type: 'ship_top' },
                { x: 1, y: 5, type: 'ship_left' },
                { x: 1, y: 6, type: 'ship' },
                { x: 1, y: 7, type: 'ship_right' },
                { x: 2, y: 1, type: 'ship_single' },
                { x: 2, y: 3, type: 'ship' },
                { x: 3, y: 3, type: 'ship_bottom' },
                { x: 3, y: 7, type: 'ship_top' },
                { x: 4, y: 1, type: 'ship_single' },
                { x: 4, y: 5, type: 'ship_single' },
                { x: 4, y: 7, type: 'ship' },
                { x: 5, y: 7, type: 'ship' },
                { x: 6, y: 0, type: 'ship_left' },
                { x: 6, y: 1, type: 'ship_right' },
                { x: 6, y: 4, type: 'ship_left' },
                { x: 6, y: 5, type: 'ship_right' },
                { x: 6, y: 7, type: 'ship_bottom' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 0, type: 'ship_left' },
                { x: 2, y: 3, type: 'ship' },
                { x: 6, y: 1, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-9-17',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [3, 1, 2, 2, 2, 5, 0, 2, 3],
        shipsColumns: [1, 2, 5, 0, 3, 2, 2, 1, 4],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 8, type: 'ship_top' },
                { x: 2, y: 4, type: 'ship_single' },
                { x: 2, y: 8, type: 'ship' },
                { x: 3, y: 2, type: 'ship_top' },
                { x: 3, y: 8, type: 'ship' },
                { x: 4, y: 2, type: 'ship' },
                { x: 4, y: 8, type: 'ship_bottom' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 2, type: 'ship_bottom' },
                { x: 5, y: 4, type: 'ship_left' },
                { x: 5, y: 5, type: 'ship' },
                { x: 5, y: 6, type: 'ship_right' },
                { x: 7, y: 4, type: 'ship_left' },
                { x: 7, y: 5, type: 'ship_right' },
                { x: 8, y: 1, type: 'ship_left' },
                { x: 8, y: 2, type: 'ship_right' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 2, y: 6, type: 'water' },
                { x: 5, y: 0, type: 'ship_single' },
                { x: 5, y: 2, type: 'ship_bottom' },
                { x: 7, y: 4, type: 'ship_left' },
                { x: 8, y: 2, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-9-18',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 2, 3, 4, 1, 3, 2, 1, 2],
        shipsColumns: [3, 3, 0, 2, 1, 1, 4, 1, 5],
        solution:
            [{ x: 0, y: 3, type: 'ship_top' },
                { x: 0, y: 8, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_top' },
                { x: 1, y: 3, type: 'ship_bottom' },
                { x: 2, y: 0, type: 'ship' },
                { x: 2, y: 6, type: 'ship_top' },
                { x: 2, y: 8, type: 'ship_top' },
                { x: 3, y: 0, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_single' },
                { x: 3, y: 6, type: 'ship' },
                { x: 3, y: 8, type: 'ship_bottom' },
                { x: 4, y: 6, type: 'ship' },
                { x: 5, y: 1, type: 'ship_top' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 5, y: 8, type: 'ship_top' },
                { x: 6, y: 1, type: 'ship' },
                { x: 6, y: 8, type: 'ship_bottom' },
                { x: 7, y: 1, type: 'ship_bottom' },
                { x: 8, y: 5, type: 'ship_single' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 8, type: 'ship_single' },
                { x: 1, y: 3, type: 'ship_bottom' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 7, y: 0, type: 'water' }],
    },
    {
        id: 'krazydad-1-9-19',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 1, 3, 2, 2, 3, 1, 0, 4],
        shipsColumns: [3, 2, 6, 1, 1, 4, 1, 2, 0],
        solution:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 2, type: 'ship' },
                { x: 0, y: 3, type: 'ship_right' },
                { x: 0, y: 5, type: 'ship_single' },
                { x: 1, y: 7, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship_top' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 2, y: 5, type: 'ship_right' },
                { x: 3, y: 0, type: 'ship_top' },
                { x: 3, y: 2, type: 'ship' },
                { x: 4, y: 0, type: 'ship' },
                { x: 4, y: 2, type: 'ship' },
                { x: 5, y: 0, type: 'ship_bottom' },
                { x: 5, y: 2, type: 'ship_bottom' },
                { x: 5, y: 7, type: 'ship_single' },
                { x: 6, y: 5, type: 'ship_single' },
                { x: 8, y: 1, type: 'ship_left' },
                { x: 8, y: 2, type: 'ship_right' },
                { x: 8, y: 5, type: 'ship_left' },
                { x: 8, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 1, type: 'ship_left' },
                { x: 0, y: 5, type: 'ship_single' },
                { x: 5, y: 0, type: 'ship_bottom' },
                { x: 5, y: 7, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-9-20',
        size: 9,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 0, 5, 1, 3, 2, 0, 4, 1],
        shipsColumns: [1, 3, 4, 2, 3, 1, 2, 3, 1],
        solution:
            [{ x: 0, y: 2, type: 'ship_single' },
                { x: 0, y: 4, type: 'ship_single' },
                { x: 0, y: 6, type: 'ship_left' },
                { x: 0, y: 7, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_left' },
                { x: 2, y: 1, type: 'ship' },
                { x: 2, y: 2, type: 'ship_right' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 2, y: 5, type: 'ship_right' },
                { x: 3, y: 8, type: 'ship_single' },
                { x: 4, y: 1, type: 'ship_left' },
                { x: 4, y: 2, type: 'ship' },
                { x: 4, y: 3, type: 'ship_right' },
                { x: 5, y: 6, type: 'ship_left' },
                { x: 5, y: 7, type: 'ship_right' },
                { x: 7, y: 1, type: 'ship_left' },
                { x: 7, y: 2, type: 'ship' },
                { x: 7, y: 3, type: 'ship' },
                { x: 7, y: 4, type: 'ship_right' },
                { x: 8, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 7, type: 'ship_right' },
                { x: 2, y: 4, type: 'ship_left' },
                { x: 3, y: 7, type: 'water' },
                { x: 5, y: 6, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-10-1',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 4, 1, 1, 4, 0, 3, 1, 5, 0],
        shipsColumns: [2, 0, 4, 3, 2, 1, 0, 2, 4, 2],
        solution:
            [{ x: 0, y: 2, type: 'ship_top' },
                { x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 7, type: 'ship_left' },
                { x: 1, y: 8, type: 'ship_right' },
                { x: 2, y: 2, type: 'ship_bottom' },
                { x: 3, y: 9, type: 'ship_top' },
                { x: 4, y: 3, type: 'ship_left' },
                { x: 4, y: 4, type: 'ship_right' },
                { x: 4, y: 7, type: 'ship_single' },
                { x: 4, y: 9, type: 'ship_bottom' },
                { x: 6, y: 0, type: 'ship_single' },
                { x: 6, y: 3, type: 'ship_single' },
                { x: 6, y: 8, type: 'ship_top' },
                { x: 7, y: 8, type: 'ship' },
                { x: 8, y: 2, type: 'ship_left' },
                { x: 8, y: 3, type: 'ship' },
                { x: 8, y: 4, type: 'ship' },
                { x: 8, y: 5, type: 'ship_right' },
                { x: 8, y: 8, type: 'ship_bottom' }],
        puzzle:
            [{ x: 1, y: 8, type: 'ship_right' },
                { x: 4, y: 0, type: 'water' },
                { x: 4, y: 9, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-10-2',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 3, 0, 5, 0, 4, 0, 0, 4, 2],
        shipsColumns: [2, 1, 3, 1, 2, 2, 5, 2, 1, 1],
        solution:
            [{ x: 0, y: 6, type: 'ship_top' },
                { x: 0, y: 9, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 4, type: 'ship_single' },
                { x: 1, y: 6, type: 'ship_bottom' },
                { x: 3, y: 0, type: 'ship_left' },
                { x: 3, y: 1, type: 'ship' },
                { x: 3, y: 2, type: 'ship_right' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 7, type: 'ship_right' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 5, y: 4, type: 'ship_left' },
                { x: 5, y: 5, type: 'ship' },
                { x: 5, y: 6, type: 'ship_right' },
                { x: 8, y: 5, type: 'ship_left' },
                { x: 8, y: 6, type: 'ship' },
                { x: 8, y: 7, type: 'ship' },
                { x: 8, y: 8, type: 'ship_right' },
                { x: 9, y: 2, type: 'ship_left' },
                { x: 9, y: 3, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 9, type: 'water' },
                { x: 3, y: 6, type: 'ship_left' },
                { x: 3, y: 8, type: 'water' },
                { x: 5, y: 2, type: 'ship_single' },
                { x: 9, y: 3, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-10-3',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 2, 0, 1, 2, 2, 4, 2, 2, 3],
        shipsColumns: [0, 2, 2, 2, 2, 1, 5, 1, 3, 2],
        solution:
            [{ x: 0, y: 1, type: 'ship_top' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 1, type: 'ship_bottom' },
                { x: 1, y: 3, type: 'ship_single' },
                { x: 3, y: 8, type: 'ship_top' },
                { x: 4, y: 6, type: 'ship_top' },
                { x: 4, y: 8, type: 'ship' },
                { x: 5, y: 6, type: 'ship' },
                { x: 5, y: 8, type: 'ship_bottom' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 4, type: 'ship_right' },
                { x: 6, y: 6, type: 'ship' },
                { x: 7, y: 6, type: 'ship_bottom' },
                { x: 7, y: 9, type: 'ship_top' },
                { x: 8, y: 2, type: 'ship_single' },
                { x: 8, y: 9, type: 'ship_bottom' },
                { x: 9, y: 4, type: 'ship_left' },
                { x: 9, y: 5, type: 'ship_right' },
                { x: 9, y: 7, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 6, y: 1, type: 'water' },
                { x: 8, y: 9, type: 'ship_bottom' },
                { x: 9, y: 5, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-10-4',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 3, 3, 1, 3, 1, 0, 1, 5, 1],
        shipsColumns: [3, 0, 0, 4, 2, 4, 1, 0, 4, 2],
        solution:
            [{ x: 0, y: 4, type: 'ship_left' },
                { x: 0, y: 5, type: 'ship_right' },
                { x: 1, y: 0, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship_left' },
                { x: 1, y: 9, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_bottom' },
                { x: 2, y: 3, type: 'ship_top' },
                { x: 2, y: 5, type: 'ship_single' },
                { x: 3, y: 3, type: 'ship' },
                { x: 4, y: 3, type: 'ship' },
                { x: 4, y: 5, type: 'ship_single' },
                { x: 4, y: 9, type: 'ship_single' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 7, y: 8, type: 'ship_top' },
                { x: 8, y: 0, type: 'ship_single' },
                { x: 8, y: 4, type: 'ship_left' },
                { x: 8, y: 5, type: 'ship' },
                { x: 8, y: 6, type: 'ship_right' },
                { x: 8, y: 8, type: 'ship' },
                { x: 9, y: 8, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 5, type: 'ship_right' },
                { x: 3, y: 0, type: 'water' },
                { x: 4, y: 0, type: 'water' },
                { x: 5, y: 0, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-5',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [0, 3, 1, 4, 1, 0, 3, 1, 4, 3],
        shipsColumns: [3, 3, 4, 0, 2, 2, 1, 1, 3, 1],
        solution:
            [{ x: 1, y: 0, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship_top' },
                { x: 1, y: 4, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship' },
                { x: 3, y: 2, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_left' },
                { x: 3, y: 5, type: 'ship_right' },
                { x: 3, y: 8, type: 'ship_single' },
                { x: 4, y: 0, type: 'ship_single' },
                { x: 6, y: 1, type: 'ship_top' },
                { x: 6, y: 8, type: 'ship_left' },
                { x: 6, y: 9, type: 'ship_right' },
                { x: 7, y: 1, type: 'ship_bottom' },
                { x: 8, y: 5, type: 'ship_left' },
                { x: 8, y: 6, type: 'ship' },
                { x: 8, y: 7, type: 'ship' },
                { x: 8, y: 8, type: 'ship_right' },
                { x: 9, y: 0, type: 'ship_left' },
                { x: 9, y: 1, type: 'ship' },
                { x: 9, y: 2, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 4, type: 'ship_single' },
                { x: 4, y: 0, type: 'ship_single' },
                { x: 7, y: 1, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-10-6',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 4, 3, 3, 0, 3, 3, 0, 0, 2],
        shipsColumns: [0, 4, 0, 1, 4, 1, 4, 0, 5, 1],
        solution:
            [{ x: 0, y: 4, type: 'ship_top' },
                { x: 0, y: 8, type: 'ship_top' },
                { x: 1, y: 1, type: 'ship_top' },
                { x: 1, y: 4, type: 'ship' },
                { x: 1, y: 6, type: 'ship_single' },
                { x: 1, y: 8, type: 'ship' },
                { x: 2, y: 1, type: 'ship' },
                { x: 2, y: 4, type: 'ship_bottom' },
                { x: 2, y: 8, type: 'ship' },
                { x: 3, y: 1, type: 'ship_bottom' },
                { x: 3, y: 6, type: 'ship_single' },
                { x: 3, y: 8, type: 'ship_bottom' },
                { x: 5, y: 3, type: 'ship_left' },
                { x: 5, y: 4, type: 'ship_right' },
                { x: 5, y: 6, type: 'ship_single' },
                { x: 6, y: 1, type: 'ship_single' },
                { x: 6, y: 8, type: 'ship_left' },
                { x: 6, y: 9, type: 'ship_right' },
                { x: 9, y: 5, type: 'ship_left' },
                { x: 9, y: 6, type: 'ship_right' }],
        puzzle:
            [{ x: 2, y: 4, type: 'ship_bottom' },
                { x: 5, y: 4, type: 'ship_right' },
                { x: 6, y: 1, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-10-7',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [0, 1, 1, 1, 5, 0, 5, 2, 4, 1],
        shipsColumns: [4, 1, 1, 2, 4, 1, 3, 3, 0, 1],
        solution:
            [{ x: 1, y: 4, type: 'ship_single' },
                { x: 2, y: 0, type: 'ship_top' },
                { x: 3, y: 0, type: 'ship' },
                { x: 4, y: 0, type: 'ship_bottom' },
                { x: 4, y: 3, type: 'ship_left' },
                { x: 4, y: 4, type: 'ship_right' },
                { x: 4, y: 6, type: 'ship_left' },
                { x: 4, y: 7, type: 'ship_right' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 4, type: 'ship_right' },
                { x: 6, y: 6, type: 'ship_left' },
                { x: 6, y: 7, type: 'ship_right' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 9, type: 'ship_single' },
                { x: 8, y: 4, type: 'ship_left' },
                { x: 8, y: 5, type: 'ship' },
                { x: 8, y: 6, type: 'ship' },
                { x: 8, y: 7, type: 'ship_right' },
                { x: 9, y: 1, type: 'ship_single' }],
        puzzle:
            [{ x: 2, y: 0, type: 'ship_top' },
                { x: 8, y: 5, type: 'ship' }],
    },
    {
        id: 'krazydad-1-10-8',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 1, 1, 2, 2, 2, 1, 3, 3, 3],
        shipsColumns: [1, 2, 4, 0, 6, 0, 1, 2, 0, 4],
        solution:
            [{ x: 0, y: 2, type: 'ship_top' },
                { x: 0, y: 7, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship' },
                { x: 2, y: 2, type: 'ship' },
                { x: 3, y: 2, type: 'ship_bottom' },
                { x: 3, y: 4, type: 'ship_top' },
                { x: 4, y: 4, type: 'ship' },
                { x: 4, y: 9, type: 'ship_top' },
                { x: 5, y: 4, type: 'ship_bottom' },
                { x: 5, y: 9, type: 'ship_bottom' },
                { x: 6, y: 6, type: 'ship_single' },
                { x: 7, y: 1, type: 'ship_single' },
                { x: 7, y: 4, type: 'ship_top' },
                { x: 7, y: 9, type: 'ship_top' },
                { x: 8, y: 4, type: 'ship' },
                { x: 8, y: 7, type: 'ship_single' },
                { x: 8, y: 9, type: 'ship_bottom' },
                { x: 9, y: 0, type: 'ship_left' },
                { x: 9, y: 1, type: 'ship_right' },
                { x: 9, y: 4, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 2, type: 'ship_top' },
                { x: 0, y: 7, type: 'ship_single' },
                { x: 6, y: 6, type: 'ship_single' },
                { x: 8, y: 9, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-10-9',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 1, 2, 2, 2, 2, 2, 1, 4, 3],
        shipsColumns: [0, 2, 1, 0, 4, 1, 5, 2, 0, 5],
        solution:
            [{ x: 0, y: 5, type: 'ship_single' },
                { x: 1, y: 9, type: 'ship_single' },
                { x: 2, y: 6, type: 'ship_left' },
                { x: 2, y: 7, type: 'ship_right' },
                { x: 3, y: 1, type: 'ship_single' },
                { x: 3, y: 4, type: 'ship_top' },
                { x: 4, y: 4, type: 'ship' },
                { x: 4, y: 6, type: 'ship_top' },
                { x: 5, y: 4, type: 'ship_bottom' },
                { x: 5, y: 6, type: 'ship' },
                { x: 6, y: 6, type: 'ship_bottom' },
                { x: 6, y: 9, type: 'ship_top' },
                { x: 7, y: 9, type: 'ship' },
                { x: 8, y: 1, type: 'ship_left' },
                { x: 8, y: 2, type: 'ship_right' },
                { x: 8, y: 4, type: 'ship_single' },
                { x: 8, y: 9, type: 'ship' },
                { x: 9, y: 6, type: 'ship_left' },
                { x: 9, y: 7, type: 'ship_right' },
                { x: 9, y: 9, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 5, type: 'ship_single' },
                { x: 2, y: 6, type: 'ship_left' },
                { x: 3, y: 1, type: 'ship_single' },
                { x: 7, y: 9, type: 'ship' },
                { x: 9, y: 2, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-10',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 1, 0, 2, 1, 3, 1, 5, 0, 5],
        shipsColumns: [0, 4, 3, 2, 0, 2, 4, 2, 2, 1],
        solution:
            [{ x: 0, y: 1, type: 'ship_single' },
                { x: 0, y: 6, type: 'ship_top' },
                { x: 1, y: 6, type: 'ship_bottom' },
                { x: 3, y: 1, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_single' },
                { x: 4, y: 1, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_left' },
                { x: 5, y: 6, type: 'ship' },
                { x: 5, y: 7, type: 'ship_right' },
                { x: 6, y: 2, type: 'ship_top' },
                { x: 7, y: 2, type: 'ship_bottom' },
                { x: 7, y: 6, type: 'ship_left' },
                { x: 7, y: 7, type: 'ship' },
                { x: 7, y: 8, type: 'ship' },
                { x: 7, y: 9, type: 'ship_right' },
                { x: 9, y: 1, type: 'ship_left' },
                { x: 9, y: 2, type: 'ship' },
                { x: 9, y: 3, type: 'ship_right' },
                { x: 9, y: 5, type: 'ship_single' },
                { x: 9, y: 8, type: 'ship_single' }],
        puzzle:
            [{ x: 6, y: 2, type: 'ship_top' },
                { x: 7, y: 6, type: 'ship_left' },
                { x: 9, y: 6, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-11',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 4, 0, 1, 3, 3, 1, 1, 3, 3],
        shipsColumns: [1, 0, 2, 4, 1, 1, 4, 0, 6, 1],
        solution:
            [{ x: 0, y: 6, type: 'ship_single' },
                { x: 1, y: 2, type: 'ship_left' },
                { x: 1, y: 3, type: 'ship' },
                { x: 1, y: 4, type: 'ship_right' },
                { x: 1, y: 8, type: 'ship_single' },
                { x: 3, y: 6, type: 'ship_top' },
                { x: 4, y: 6, type: 'ship' },
                { x: 4, y: 8, type: 'ship_left' },
                { x: 4, y: 9, type: 'ship_right' },
                { x: 5, y: 2, type: 'ship_left' },
                { x: 5, y: 3, type: 'ship_right' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 6, y: 8, type: 'ship_top' },
                { x: 7, y: 8, type: 'ship' },
                { x: 8, y: 3, type: 'ship_top' },
                { x: 8, y: 5, type: 'ship_single' },
                { x: 8, y: 8, type: 'ship' },
                { x: 9, y: 0, type: 'ship_single' },
                { x: 9, y: 3, type: 'ship_bottom' },
                { x: 9, y: 8, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 3, type: 'water' },
                { x: 1, y: 6, type: 'water' },
                { x: 3, y: 3, type: 'water' },
                { x: 4, y: 8, type: 'ship_left' },
                { x: 6, y: 6, type: 'water' },
                { x: 7, y: 3, type: 'water' },
                { x: 9, y: 0, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-10-12',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 4, 0, 2, 1, 3, 2, 2, 5, 0],
        shipsColumns: [6, 1, 2, 2, 1, 3, 1, 1, 2, 1],
        solution:
            [{ x: 0, y: 5, type: 'ship_single' },
                { x: 1, y: 0, type: 'ship_left' },
                { x: 1, y: 1, type: 'ship' },
                { x: 1, y: 2, type: 'ship' },
                { x: 1, y: 3, type: 'ship_right' },
                { x: 3, y: 0, type: 'ship_top' },
                { x: 3, y: 9, type: 'ship_single' },
                { x: 4, y: 0, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 5, y: 7, type: 'ship_left' },
                { x: 5, y: 8, type: 'ship_right' },
                { x: 6, y: 0, type: 'ship_top' },
                { x: 6, y: 5, type: 'ship_bottom' },
                { x: 7, y: 0, type: 'ship' },
                { x: 7, y: 8, type: 'ship_single' },
                { x: 8, y: 0, type: 'ship_bottom' },
                { x: 8, y: 2, type: 'ship_left' },
                { x: 8, y: 3, type: 'ship' },
                { x: 8, y: 4, type: 'ship_right' },
                { x: 8, y: 6, type: 'ship_single' }],
        puzzle:
            [{ x: 1, y: 4, type: 'water' },
                { x: 3, y: 9, type: 'ship_single' },
                { x: 4, y: 5, type: 'water' },
                { x: 5, y: 7, type: 'ship_left' },
                { x: 8, y: 0, type: 'ship_bottom' },
                { x: 8, y: 5, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-13',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 4, 4, 0, 2, 0, 1, 4, 1, 2],
        shipsColumns: [0, 4, 1, 3, 2, 3, 0, 0, 4, 3],
        solution:
            [{ x: 0, y: 1, type: 'ship_top' },
                { x: 0, y: 8, type: 'ship_top' },
                { x: 1, y: 1, type: 'ship' },
                { x: 1, y: 3, type: 'ship_top' },
                { x: 1, y: 5, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship' },
                { x: 2, y: 1, type: 'ship_bottom' },
                { x: 2, y: 3, type: 'ship_bottom' },
                { x: 2, y: 5, type: 'ship_bottom' },
                { x: 2, y: 8, type: 'ship_bottom' },
                { x: 4, y: 4, type: 'ship_single' },
                { x: 4, y: 9, type: 'ship_single' },
                { x: 6, y: 8, type: 'ship_single' },
                { x: 7, y: 2, type: 'ship_left' },
                { x: 7, y: 3, type: 'ship' },
                { x: 7, y: 4, type: 'ship' },
                { x: 7, y: 5, type: 'ship_right' },
                { x: 8, y: 9, type: 'ship_top' },
                { x: 9, y: 1, type: 'ship_single' },
                { x: 9, y: 9, type: 'ship_bottom' }],
        puzzle:
            [{ x: 2, y: 8, type: 'ship_bottom' },
                { x: 4, y: 3, type: 'water' },
                { x: 4, y: 8, type: 'water' },
                { x: 7, y: 2, type: 'ship_left' },
                { x: 9, y: 1, type: 'ship_single' }],
    },
    {
        id: 'krazydad-1-10-14',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [5, 0, 2, 0, 2, 1, 2, 3, 3, 2],
        shipsColumns: [1, 4, 1, 4, 1, 0, 2, 1, 5, 1],
        solution:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 0, y: 2, type: 'ship_left' },
                { x: 0, y: 3, type: 'ship' },
                { x: 0, y: 4, type: 'ship_right' },
                { x: 0, y: 6, type: 'ship_single' },
                { x: 2, y: 7, type: 'ship_left' },
                { x: 2, y: 8, type: 'ship_right' },
                { x: 4, y: 8, type: 'ship_left' },
                { x: 4, y: 9, type: 'ship_right' },
                { x: 5, y: 3, type: 'ship_single' },
                { x: 6, y: 1, type: 'ship_top' },
                { x: 6, y: 8, type: 'ship_top' },
                { x: 7, y: 1, type: 'ship' },
                { x: 7, y: 6, type: 'ship_single' },
                { x: 7, y: 8, type: 'ship' },
                { x: 8, y: 1, type: 'ship' },
                { x: 8, y: 3, type: 'ship_top' },
                { x: 8, y: 8, type: 'ship_bottom' },
                { x: 9, y: 1, type: 'ship_bottom' },
                { x: 9, y: 3, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 0, y: 9, type: 'water' },
                { x: 2, y: 7, type: 'ship_left' },
                { x: 4, y: 6, type: 'water' },
                { x: 5, y: 1, type: 'water' },
                { x: 6, y: 3, type: 'water' },
                { x: 7, y: 6, type: 'ship_single' },
                { x: 8, y: 9, type: 'water' },
                { x: 9, y: 3, type: 'ship_bottom' }],
    },
    {
        id: 'krazydad-1-10-15',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [1, 2, 2, 3, 1, 1, 4, 2, 1, 3],
        shipsColumns: [3, 0, 3, 4, 0, 4, 0, 2, 1, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 1, y: 5, type: 'ship_single' },
                { x: 1, y: 9, type: 'ship_top' },
                { x: 2, y: 2, type: 'ship_top' },
                { x: 2, y: 9, type: 'ship' },
                { x: 3, y: 2, type: 'ship' },
                { x: 3, y: 5, type: 'ship_single' },
                { x: 3, y: 9, type: 'ship_bottom' },
                { x: 4, y: 2, type: 'ship_bottom' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 6, y: 0, type: 'ship_top' },
                { x: 6, y: 3, type: 'ship_top' },
                { x: 6, y: 5, type: 'ship_bottom' },
                { x: 6, y: 7, type: 'ship_single' },
                { x: 7, y: 0, type: 'ship_bottom' },
                { x: 7, y: 3, type: 'ship' },
                { x: 8, y: 3, type: 'ship' },
                { x: 9, y: 3, type: 'ship_bottom' },
                { x: 9, y: 7, type: 'ship_left' },
                { x: 9, y: 8, type: 'ship_right' }],
        puzzle:
            [{ x: 0, y: 0, type: 'ship_single' },
                { x: 2, y: 2, type: 'ship_top' },
                { x: 5, y: 5, type: 'ship_top' },
                { x: 9, y: 7, type: 'ship_left' }],
    },
    {
        id: 'krazydad-1-10-16',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 0, 1, 2, 3, 2, 1, 3, 5, 1],
        shipsColumns: [2, 3, 1, 3, 1, 0, 3, 0, 2, 5],
        solution:
            [{ x: 0, y: 4, type: 'ship_single' },
                { x: 0, y: 8, type: 'ship_single' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 3, y: 3, type: 'ship_top' },
                { x: 3, y: 9, type: 'ship_top' },
                { x: 4, y: 1, type: 'ship_top' },
                { x: 4, y: 3, type: 'ship_bottom' },
                { x: 4, y: 9, type: 'ship' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 9, type: 'ship_bottom' },
                { x: 6, y: 6, type: 'ship_top' },
                { x: 7, y: 6, type: 'ship' },
                { x: 7, y: 8, type: 'ship_left' },
                { x: 7, y: 9, type: 'ship_right' },
                { x: 8, y: 0, type: 'ship_left' },
                { x: 8, y: 1, type: 'ship' },
                { x: 8, y: 2, type: 'ship' },
                { x: 8, y: 3, type: 'ship_right' },
                { x: 8, y: 6, type: 'ship_bottom' },
                { x: 9, y: 9, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 8, type: 'ship_single' },
                { x: 5, y: 1, type: 'ship_bottom' },
                { x: 5, y: 4, type: 'water' },
                { x: 5, y: 6, type: 'water' },
                { x: 7, y: 0, type: 'water' },
                { x: 8, y: 3, type: 'ship_right' }],
    },
    {
        id: 'krazydad-1-10-17',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [5, 1, 5, 0, 1, 1, 2, 2, 3, 0],
        shipsColumns: [2, 2, 1, 3, 2, 1, 2, 1, 3, 3],
        solution:
            [{ x: 0, y: 0, type: 'ship_left' },
                { x: 0, y: 1, type: 'ship_right' },
                { x: 0, y: 3, type: 'ship_left' },
                { x: 0, y: 4, type: 'ship_right' },
                { x: 0, y: 8, type: 'ship_top' },
                { x: 1, y: 8, type: 'ship' },
                { x: 2, y: 1, type: 'ship_left' },
                { x: 2, y: 2, type: 'ship' },
                { x: 2, y: 3, type: 'ship' },
                { x: 2, y: 4, type: 'ship_right' },
                { x: 2, y: 8, type: 'ship_bottom' },
                { x: 4, y: 6, type: 'ship_top' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 6, y: 3, type: 'ship_single' },
                { x: 6, y: 9, type: 'ship_top' },
                { x: 7, y: 7, type: 'ship_single' },
                { x: 7, y: 9, type: 'ship' },
                { x: 8, y: 0, type: 'ship_single' },
                { x: 8, y: 5, type: 'ship_single' },
                { x: 8, y: 9, type: 'ship_bottom' }],
        puzzle:
            [{ x: 0, y: 1, type: 'ship_right' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 7, y: 7, type: 'ship_single' },
                { x: 8, y: 3, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-18',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [2, 4, 2, 0, 2, 3, 2, 3, 0, 2],
        shipsColumns: [1, 0, 3, 3, 1, 0, 5, 0, 5, 2],
        solution:
            [{ x: 0, y: 3, type: 'ship_top' },
                { x: 0, y: 6, type: 'ship_top' },
                { x: 1, y: 3, type: 'ship' },
                { x: 1, y: 6, type: 'ship_bottom' },
                { x: 1, y: 8, type: 'ship_left' },
                { x: 1, y: 9, type: 'ship_right' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 2, y: 3, type: 'ship_bottom' },
                { x: 4, y: 2, type: 'ship_top' },
                { x: 4, y: 8, type: 'ship_top' },
                { x: 5, y: 2, type: 'ship_bottom' },
                { x: 5, y: 6, type: 'ship_top' },
                { x: 5, y: 8, type: 'ship' },
                { x: 6, y: 6, type: 'ship' },
                { x: 6, y: 8, type: 'ship' },
                { x: 7, y: 4, type: 'ship_single' },
                { x: 7, y: 6, type: 'ship_bottom' },
                { x: 7, y: 8, type: 'ship_bottom' },
                { x: 9, y: 2, type: 'ship_single' },
                { x: 9, y: 9, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 6, type: 'ship_top' },
                { x: 2, y: 0, type: 'ship_single' },
                { x: 5, y: 3, type: 'water' },
                { x: 7, y: 6, type: 'ship_bottom' },
                { x: 9, y: 4, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-19',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [0, 2, 0, 5, 1, 2, 4, 2, 2, 2],
        shipsColumns: [1, 1, 3, 2, 3, 0, 4, 0, 2, 4],
        solution:
            [{ x: 1, y: 8, type: 'ship_left' },
                { x: 1, y: 9, type: 'ship_right' },
                { x: 3, y: 1, type: 'ship_left' },
                { x: 3, y: 2, type: 'ship' },
                { x: 3, y: 3, type: 'ship' },
                { x: 3, y: 4, type: 'ship_right' },
                { x: 3, y: 6, type: 'ship_single' },
                { x: 4, y: 9, type: 'ship_top' },
                { x: 5, y: 6, type: 'ship_top' },
                { x: 5, y: 9, type: 'ship_bottom' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 6, y: 3, type: 'ship' },
                { x: 6, y: 4, type: 'ship_right' },
                { x: 6, y: 6, type: 'ship' },
                { x: 7, y: 0, type: 'ship_single' },
                { x: 7, y: 6, type: 'ship_bottom' },
                { x: 8, y: 2, type: 'ship_single' },
                { x: 8, y: 4, type: 'ship_single' },
                { x: 9, y: 8, type: 'ship_left' },
                { x: 9, y: 9, type: 'ship_right' }],
        puzzle:
            [{ x: 1, y: 8, type: 'ship_left' },
                { x: 4, y: 9, type: 'ship_top' },
                { x: 6, y: 2, type: 'ship_left' },
                { x: 9, y: 4, type: 'water' }],
    },
    {
        id: 'krazydad-1-10-20',
        size: 10,
        ships:
            [{ size: 1, count: 4 },
                { size: 2, count: 3 },
                { size: 3, count: 2 },
                { size: 4, count: 1 }],
        shipsRows: [4, 2, 1, 2, 3, 2, 1, 1, 4, 0],
        shipsColumns: [1, 0, 2, 4, 1, 2, 6, 0, 2, 2],
        solution:
            [{ x: 0, y: 5, type: 'ship_left' },
                { x: 0, y: 6, type: 'ship_right' },
                { x: 0, y: 8, type: 'ship_left' },
                { x: 0, y: 9, type: 'ship_right' },
                { x: 1, y: 2, type: 'ship_left' },
                { x: 1, y: 3, type: 'ship_right' },
                { x: 2, y: 6, type: 'ship_top' },
                { x: 3, y: 3, type: 'ship_top' },
                { x: 3, y: 6, type: 'ship' },
                { x: 4, y: 0, type: 'ship_single' },
                { x: 4, y: 3, type: 'ship' },
                { x: 4, y: 6, type: 'ship' },
                { x: 5, y: 3, type: 'ship_bottom' },
                { x: 5, y: 6, type: 'ship_bottom' },
                { x: 6, y: 9, type: 'ship_single' },
                { x: 7, y: 2, type: 'ship_single' },
                { x: 8, y: 4, type: 'ship_left' },
                { x: 8, y: 5, type: 'ship' },
                { x: 8, y: 6, type: 'ship_right' },
                { x: 8, y: 8, type: 'ship_single' }],
        puzzle:
            [{ x: 0, y: 9, type: 'ship_right' },
                { x: 4, y: 0, type: 'ship_single' },
                { x: 6, y: 9, type: 'ship_single' }],
    },
];
